In [4]:
from numpy import random

i = random.randint(10)

print(i)

6


In [6]:
from numpy import random

i = random.rand()

print(i)

0.4877750410028334


In [7]:
from numpy import random

i = random.rand(11)

print(i)

[0.57857691 0.96800805 0.5505033  0.86634557 0.73586272 0.60907124
 0.61730249 0.88923457 0.94882981 0.6711312  0.61506124]


In [9]:
from numpy import random

i = random.randint(100,size=(10))

print(i)

[48 75 75 67 62 98 69 59 75 68]


In [11]:
from numpy import random

i = random.randint(100,size=(3,5))

print(i)

[[81 16 10 61 30]
 [15 43 67 49 28]
 [82 46 65  7 58]]


In [12]:
from numpy import random

i = random.randint(100,size=(5,5))

print(i)

[[11 44 85 94 67]
 [66  5 70 71 61]
 [98 63 17 50 31]
 [ 9 93 33 85 50]
 [44 63 59 59  3]]


In [13]:
from numpy import random

i = random.randint(100,size=(3,5,2))

print(i)

[[[61 18]
  [75 51]
  [81 34]
  [39 97]
  [52 13]]

 [[61 30]
  [22 26]
  [18 16]
  [65 88]
  [19 26]]

 [[70 63]
  [39 30]
  [ 8 21]
  [51 91]
  [25 33]]]


In [15]:
from numpy import random

i = random.rand(3,5)

print(i)

[[0.67995138 0.38117164 0.0964272  0.13297674 0.5769471 ]
 [0.18452874 0.69740213 0.91786787 0.92371704 0.70744551]
 [0.90856298 0.28086034 0.99156445 0.57263712 0.34277481]]


In [21]:
list1 = [10,20,30,40,50,60,70,80,90]

i = random.choice(list1)

print(i)

60


In [24]:
list1 = [10,20,30,40,50,60,70,80,90]

i = random.choice(list1,size=(3,5))

print(i)

[[60 70 90 70 90]
 [60 30 30 40 30]
 [80 60 20 90 80]]


In [25]:
list1 = [10,20,30,40,50,60,70,80,90]

i = random.choice(list1,size=(3,5,2))

print(i)

[[[80 80]
  [70 50]
  [20 10]
  [80 40]
  [60 20]]

 [[20 80]
  [40 30]
  [40 80]
  [70 80]
  [40 10]]

 [[80 70]
  [40 30]
  [60 60]
  [20 90]
  [20 90]]]


In [26]:
import numpy as np

i = np.array([1,2,3,4,5])

j = i.copy() #j = copy data

i[0] = 10
i[1] = 20

print(i)
print(j)

[10 20  3  4  5]
[1 2 3 4 5]


In [27]:
import numpy as np

i = np.array([1,2,3,4,5])

j = i.view()   #j = view data

i[0] = 10
i[1] = 20

print(i)
print(j)

[10 20  3  4  5]
[10 20  3  4  5]


In [29]:
import numpy as np

i = np.array([1,2,3,4,5])

j = i.view()   #j = view data

i[0] = 10
i[1] = 20

print(i)
print(j)
print()

print(i.base)
print(j.base)

[10 20  3  4  5]
[10 20  3  4  5]

None
[10 20  3  4  5]
